"""Symbols exposed on query.core for execute_run_ask and monkeypatch(query.core.*) tests."""
from __future__ import annotations

from chroma_client import get_client
from constants import (
    DB_PATH,
    LLMLI_COLLECTION,
    DEFAULT_MODEL,
    DEFAULT_N_RESULTS,
    MAX_CHUNKS_PER_FILE,
)
from embeddings import get_embedding_function
from image_embeddings import get_image_embedding_adapter, image_collection_name
from load_config import load_config, get_archetype, get_archetype_optional, get_query_options
from reranker import RERANK_STAGE1_N, is_reranker_enabled, rerank as rerank_chunks
from state import get_silo_display_name, get_silo_prompt_override, resolve_silo_to_slug
from style import bold, dim, label_style

from query.academic import parse_academic_query
from query.academic_resolver import run_academic_resolver
from query.catalog import (
    build_structure_extension_count,
    build_structure_inventory,
    build_structure_outline,
    build_structure_recent,
    list_files_from_year,
    parse_file_list_year_request,
    parse_structure_request,
    rank_scope_candidates,
    validate_catalog_freshness,
)
from query.code_language import (
    CODE_EXTENSIONS,
    compute_code_language_from_chroma,
    format_code_language_answer,
    format_code_language_year_answer,
    get_code_language_stats_from_manifest_year,
    get_code_language_stats_from_registry,
    get_code_sources_from_manifest_year,
    summarize_code_activity_year,
)
from query.context import (
    DOC_TYPE_BONUS,
    RECENCY_WEIGHT,
    context_block,
    context_has_timing_patterns,
    path_looks_like_tax_return,
    query_asks_for_agi,
    query_implies_measurement_intent,
    query_implies_recency,
    query_implies_speed,
    query_mentioned_years,
    recency_score,
)
from query.expansion import decompose_temporal_query, expand_query
from query.formatting import (
    find_direct_address_contract_violations,
    format_source,
    linkify_sources_in_answer,
    normalize_answer_direct_address,
    normalize_inline_numbered_lists,
    normalize_ownership_claims,
    normalize_sentence_start,
    normalize_uncertainty_tone,
    render_sources_footer,
    sanitize_answer_metadata_artifacts,
    style_answer,
    wrap_reflection_answer,
)
from query.guardrails import (
    run_csv_rank_lookup_guardrail,
    run_direct_value_consistency_guardrail,
    run_field_lookup_guardrail,
    run_income_year_total_guardrail,
)
from query.intent import (
    INTENT_ACADEMIC_HISTORY,
    INTENT_AGGREGATE,
    INTENT_CAPABILITIES,
    INTENT_CODE_LANGUAGE,
    INTENT_EVIDENCE_PROFILE,
    INTENT_FIELD_LOOKUP,
    INTENT_FILE_LIST,
    INTENT_LOOKUP,
    INTENT_METADATA_ONLY,
    INTENT_MONEY_YEAR_TOTAL,
    INTENT_PROJECT_COUNT,
    INTENT_REFLECT,
    INTENT_STRUCTURE,
    INTENT_TAX_QUERY,
    INTENT_TIMELINE,
    effective_k,
    route_intent,
)
from query.metadata import aggregate_metadata, format_metadata_answer, parse_metadata_request
from query.project_count import compute_project_count, format_project_count
from query.retrieval import (
    PROFILE_LEXICAL_PHRASES,
    MAX_LEXICAL_FOR_RRF,
    all_dists_above_threshold,
    dedup_by_chunk_hash,
    diversify_by_source,
    diversify_by_silo,
    extract_direct_lexical_terms,
    filter_by_triggers,
    max_chunks_for_intent,
    max_silo_chunks_for_intent,
    relevance_max_distance,
    resolve_subscope,
    rrf_merge,
    run_hybrid_retrieve,
    soft_promote_silo_diversity,
    sort_by_academic_priority,
    sort_by_image_chunk_priority,
    sort_by_source_priority,
    source_extension_rank_map,
    source_priority_score,
)
from query.scope_binding import bind_scope_from_query, detect_filetype_hints, rank_silos_by_catalog_tokens
from query.tax_resolver import run_tax_resolver
from query.timeline import build_timeline_from_manifest, format_timeline_answer, parse_timeline_request
from query.trace import write_trace

from query.core_support import (
    WEAK_SCOPE_TOP_DISTANCE,
    QueryPolicyError,
    _academic_support_stats,
    _combine_where_and,
    _compose_answer_system_prompt,
    _confidence_assessment,
    _confidence_signal,
    _distinct_silo_count,
    _group_context_by_silo,
    _has_query_evidence_overlap,
    _hydrate_image_summary_docs,
    _is_code_activity_year_lookup,
    _is_unified_analytical_query,
    _llm_summarize_structure,
    _normalize_silo_token,
    _query_image_collection,
    _query_is_image_relevant,
    _quiet_text_only,
    _rank_candidate_silos,
    _repair_direct_address_answer,
    _resolve_unified_silo_prompt,
    _safe_query,
    _single_year_from_query,
    _strip_hash_suffix,
    _top_distance,
    _build_recency_hints,
    _query_requests_ownership_framing,
    _query_requests_recency_hints,
)

__all__ = [
    "CODE_EXTENSIONS",
    "DB_PATH",
    "DEFAULT_MODEL",
    "DEFAULT_N_RESULTS",
    "DOC_TYPE_BONUS",
    "INTENT_ACADEMIC_HISTORY",
    "INTENT_AGGREGATE",
    "INTENT_CAPABILITIES",
    "INTENT_CODE_LANGUAGE",
    "INTENT_EVIDENCE_PROFILE",
    "INTENT_FIELD_LOOKUP",
    "INTENT_FILE_LIST",
    "INTENT_LOOKUP",
    "INTENT_METADATA_ONLY",
    "INTENT_MONEY_YEAR_TOTAL",
    "INTENT_PROJECT_COUNT",
    "INTENT_REFLECT",
    "INTENT_STRUCTURE",
    "INTENT_TAX_QUERY",
    "INTENT_TIMELINE",
    "LLMLI_COLLECTION",
    "MAX_CHUNKS_PER_FILE",
    "MAX_LEXICAL_FOR_RRF",
    "PROFILE_LEXICAL_PHRASES",
    "QueryPolicyError",
    "RECENCY_WEIGHT",
    "RERANK_STAGE1_N",
    "WEAK_SCOPE_TOP_DISTANCE",
    "_academic_support_stats",
    "_combine_where_and",
    "_compose_answer_system_prompt",
    "_confidence_assessment",
    "_confidence_signal",
    "_distinct_silo_count",
    "_group_context_by_silo",
    "_has_query_evidence_overlap",
    "_hydrate_image_summary_docs",
    "_is_code_activity_year_lookup",
    "_is_unified_analytical_query",
    "_llm_summarize_structure",
    "_normalize_silo_token",
    "_query_image_collection",
    "_query_is_image_relevant",
    "_quiet_text_only",
    "_rank_candidate_silos",
    "_repair_direct_address_answer",
    "_resolve_unified_silo_prompt",
    "_safe_query",
    "_single_year_from_query",
    "_strip_hash_suffix",
    "_top_distance",
    "_build_recency_hints",
    "_query_requests_ownership_framing",
    "_query_requests_recency_hints",
    "aggregate_metadata",
    "all_dists_above_threshold",
    "bind_scope_from_query",
    "bold",
    "compute_code_language_from_chroma",
    "compute_project_count",
    "context_block",
    "context_has_timing_patterns",
    "dedup_by_chunk_hash",
    "decompose_temporal_query",
    "detect_filetype_hints",
    "dim",
    "diversify_by_source",
    "diversify_by_silo",
    "effective_k",
    "expand_query",
    "extract_direct_lexical_terms",
    "filter_by_triggers",
    "find_direct_address_contract_violations",
    "format_code_language_answer",
    "format_code_language_year_answer",
    "format_metadata_answer",
    "format_project_count",
    "format_source",
    "format_timeline_answer",
    "get_archetype",
    "get_archetype_optional",
    "get_client",
    "get_code_language_stats_from_manifest_year",
    "get_code_language_stats_from_registry",
    "get_code_sources_from_manifest_year",
    "get_embedding_function",
    "get_image_embedding_adapter",
    "get_query_options",
    "get_silo_display_name",
    "get_silo_prompt_override",
    "image_collection_name",
    "label_style",
    "linkify_sources_in_answer",
    "list_files_from_year",
    "load_config",
    "max_chunks_for_intent",
    "max_silo_chunks_for_intent",
    "normalize_answer_direct_address",
    "normalize_inline_numbered_lists",
    "normalize_ownership_claims",
    "normalize_sentence_start",
    "normalize_uncertainty_tone",
    "parse_academic_query",
    "parse_file_list_year_request",
    "parse_metadata_request",
    "parse_structure_request",
    "parse_timeline_request",
    "path_looks_like_tax_return",
    "query_asks_for_agi",
    "query_implies_measurement_intent",
    "query_implies_recency",
    "query_implies_speed",
    "query_mentioned_years",
    "rank_scope_candidates",
    "rank_silos_by_catalog_tokens",
    "recency_score",
    "relevance_max_distance",
    "render_sources_footer",
    "resolve_silo_to_slug",
    "resolve_subscope",
    "rerank_chunks",
    "route_intent",
    "rrf_merge",
    "run_academic_resolver",
    "run_csv_rank_lookup_guardrail",
    "run_direct_value_consistency_guardrail",
    "run_field_lookup_guardrail",
    "run_hybrid_retrieve",
    "run_income_year_total_guardrail",
    "run_tax_resolver",
    "sanitize_answer_metadata_artifacts",
    "soft_promote_silo_diversity",
    "sort_by_academic_priority",
    "sort_by_image_chunk_priority",
    "sort_by_source_priority",
    "source_extension_rank_map",
    "source_priority_score",
    "style_answer",
    "summarize_code_activity_year",
    "is_reranker_enabled",
    "build_structure_extension_count",
    "build_structure_inventory",
    "build_structure_outline",
    "build_structure_recent",
    "build_timeline_from_manifest",
    "validate_catalog_freshness",
    "wrap_reflection_answer",
    "write_trace",
]
